version: "3.8"

services:
  invokeai:
    image: invokeai/invokeai:latest
    container_name: invokeai
    restart: unless-stopped
    ports:
      - "9090:9090" # interface web
    environment:
      - CLI_ARGS=--web --host 0.0.0.0
    volumes:
      - ./models:/invokeai/models
      - ./outputs:/invokeai/outputs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
